version: "2"
services:
  web:
    build: .
    env_file: 
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./mnogo-volume:/data/db
    ports:
      - "27017:27017"