version: "2"
services:
  web:
    image: limechain/cli-analytics:latest
    environment: 
      - API_ID=
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"